require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/deals', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Deal. As you add validations to Deal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Deal.create! valid_attributes
      get deals_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      deal = Deal.create! valid_attributes
      get deal_url(deal)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_deal_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      deal = Deal.create! valid_attributes
      get edit_deal_url(deal)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Deal' do
        expect do
          post deals_url, params: { deal: valid_attributes }
        end.to change(Deal, :count).by(1)
      end

      it 'redirects to the created deal' do
        post deals_url, params: { deal: valid_attributes }
        expect(response).to redirect_to(deal_url(Deal.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Deal' do
        expect do
          post deals_url, params: { deal: invalid_attributes }
        end.to change(Deal, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post deals_url, params: { deal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested deal' do
        deal = Deal.create! valid_attributes
        patch deal_url(deal), params: { deal: new_attributes }
        deal.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the deal' do
        deal = Deal.create! valid_attributes
        patch deal_url(deal), params: { deal: new_attributes }
        deal.reload
        expect(response).to redirect_to(deal_url(deal))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        deal = Deal.create! valid_attributes
        patch deal_url(deal), params: { deal: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested deal' do
      deal = Deal.create! valid_attributes
      expect do
        delete deal_url(deal)
      end.to change(Deal, :count).by(-1)
    end

    it 'redirects to the deals list' do
      deal = Deal.create! valid_attributes
      delete deal_url(deal)
      expect(response).to redirect_to(deals_url)
    end
  end
end
